// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBY3-FAvHiHRhRP6QDFD6o4liAFyC_EdM',
    appId: '1:1045670335666:web:b85550885ce1f6c772a5ab',
    messagingSenderId: '1045670335666',
    projectId: 'iot-project-b52bb',
    authDomain: 'iot-project-b52bb.firebaseapp.com',
    storageBucket: 'iot-project-b52bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3TebZ7ABztrwuOwZJWbygAaJtHwNTfY',
    appId: '1:1045670335666:android:3718cfa3b8e838b072a5ab',
    messagingSenderId: '1045670335666',
    projectId: 'iot-project-b52bb',
    storageBucket: 'iot-project-b52bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkVUVXGOkh53sOR4HdD9n_kis3wVLjvdw',
    appId: '1:1045670335666:ios:fde3b2d6b7038f2a72a5ab',
    messagingSenderId: '1045670335666',
    projectId: 'iot-project-b52bb',
    storageBucket: 'iot-project-b52bb.appspot.com',
    iosClientId: '1045670335666-83j3bvc5l2o5c8sfgv0lvf91c7e4ffe5.apps.googleusercontent.com',
    iosBundleId: 'com.iot.app',
  );
}
